#Redis
server:
  port: 8080

spring:
  profiles:
    active:
      - local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /res/**
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password:
