#Redis
server:
  port: 8080

spring:
  profiles:
    active:
      - local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /res/**


  redis:
    password: 1234
    host: 192.168.56.101
    port: 6379
